provider:
    name: youtrack
    url: https://ytcli.youtrack.cloud
project: YTCLI
local:
    states:
        - Open
        - In Progress
        - Review
        - Done
        - Closed
    priorities:
        - Critical
        - Major
        - Normal
        - Minor
    default_state: Open
    default_priority: Normal
    done_states:
        - Done
        - Closed
